version: '3'
services:
  node:
    container_name: Laudo_AI-Node
    image: node:latest
    volumes:
      - ./laudo_ai:/app
    working_dir: /app
    ports:
      - 3000:3000
    command: bash -c "apt update && apt install jq -y && npm run dev"
    environment:
      - OPENAI_API_KEY=<you_api_key>
